require 'Bibliography/version'
require 'Bibliography/Bibliography'
require 'Bibliography/LinkedList'
require 'Bibliography/Pub_periodicas'
require 'Bibliography/Libro'
require 'Bibliography/Doc_elect'
require 'Bibliography/Art_per'
require 'Bibliography/Art_rev'